FROM ubuntu

RUN apt-get update \
    && apt-get install -y git \
    && apt-get install -y nodejs \
    && apt-get install -y npm

RUN git clone https://github.com/Pyother/AreaExplorer.git
WORKDIR /frontend

RUN npm install react 
RUN npm install react-scripts

RUN npm run build

