FROM ubuntu

RUN apt-get update \
    && apt-get install -y git \
    && apt-get install -y nodejs \
    && apt-get install -y npm

RUN git clone https://github.com/Pyother/2DMapper.git
WORKDIR /2DMapper

RUN npm install react \
    && npm install react-scripts

EXPOSE 3008

CMD ["npm", "start"]
